// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Home-Tab-mod-a

#include "ui.h"

// COMPONENT Panel10

lv_obj_t * ui_Panel10_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Panel10;
    cui_Panel10 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Panel10, lv_pct(100));
    lv_obj_set_height(cui_Panel10, lv_pct(100));
    lv_obj_set_align(cui_Panel10, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Panel10, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(cui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel10, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label20;
    cui_Label20 = lv_label_create(cui_Panel10);
    lv_obj_set_width(cui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label20, "TOUCH TO WAKE");
    lv_obj_set_style_text_color(cui_Label20, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label20, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL10_NUM);
    children[UI_COMP_PANEL10_PANEL10] = cui_Panel10;
    children[UI_COMP_PANEL10_LABEL20] = cui_Label20;
    lv_obj_add_event_cb(cui_Panel10, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Panel10, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Panel10_create_hook(cui_Panel10);
    return cui_Panel10;
}

