// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Home-Tab-mod-a

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image13;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ac;
extern lv_obj_t * uic_fan;
extern lv_obj_t * uic_bulb;
extern lv_obj_t * uic_tv;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

