// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Home-Tab-mod-a

#ifndef _HOME_TAB_MOD_A_UI_H
#define _HOME_TAB_MOD_A_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_337869367);    // assets/room-temperature.png
LV_IMG_DECLARE(ui_img_441248079);    // assets/smart-house.png
LV_IMG_DECLARE(ui_img_switch_png);    // assets/switch.png
LV_IMG_DECLARE(ui_img_notification_png);    // assets/notification.png
LV_IMG_DECLARE(ui_img_silent_png);    // assets/silent.png
LV_IMG_DECLARE(ui_img_268687432);    // assets/auto-en.png
LV_IMG_DECLARE(ui_img_1995169899);    // assets/auto-dis.png
LV_IMG_DECLARE(ui_img_1800991266);    // assets/arrows-rt.png
LV_IMG_DECLARE(ui_img_temperature_png);    // assets/temperature.png
LV_IMG_DECLARE(ui_img_humidity_png);    // assets/humidity.png
LV_IMG_DECLARE(ui_img_brightness_png);    // assets/brightness.png
LV_IMG_DECLARE(ui_img_1800988192);    // assets/arrows-lt.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_1202935209);    // assets/air-conditioning.png
LV_IMG_DECLARE(ui_img_1309870313);    // assets/tv-app.png
LV_IMG_DECLARE(ui_img_fan_png);    // assets/fan.png
LV_IMG_DECLARE(ui_img_bulb_png);    // assets/bulb.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
