// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Home-Tab-mod-a

#ifndef _UI_COMP_PANEL10_H
#define _UI_COMP_PANEL10_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Panel10
#define UI_COMP_PANEL10_PANEL10 0
#define UI_COMP_PANEL10_LABEL20 1
#define _UI_COMP_PANEL10_NUM 2
lv_obj_t * ui_Panel10_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
