// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Elec_Home_Tab-mod

#include "ui.h"

void mute_btn_event_cb(lv_event_t * e)
{
	// Your code here
}

void humi_automation_cb(lv_event_t * e)
{
	// Your code here
}

void temp_automation_cb(lv_event_t * e)
{
	// Your code here
}
