// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Home-Tab-mod-a

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern void ui_event_Panel8(lv_event_t * e);
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image4;
extern void ui_event_Panel9(lv_event_t * e);
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button1;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
// CUSTOM VARIABLES
extern lv_obj_t * uic_time;
extern lv_obj_t * uic_day;
extern lv_obj_t * uic_date;
extern lv_obj_t * uic_MuteBtn;
extern lv_obj_t * uic_autoDisBtn;
extern lv_obj_t * uic_WakePanel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

