// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Home-Tab-mod-a

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Chart3;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_temperature;
extern lv_obj_t * uic_tempBar;
extern lv_obj_t * uic_humidity;
extern lv_obj_t * uic_humiBar;
extern lv_obj_t * uic_light;
extern lv_obj_t * uic_lightBar;
extern lv_obj_t * uic_tempChart;
extern lv_obj_t * uic_humiChart;
extern lv_obj_t * uic_lightChart;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

